APPDESCRIP-28: update erm-usage/files interface id to be valid for Eureka platform
folio-org/mod-erm-usage pull request #179
Opened 2024-07-29 09:31 UTC by yaroslav-kiriak

[APPDESCRIP-28](https://folio-org.atlassian.net/browse/APPDESCRIP-28)

**Related PR:** https://github.com/folio-org/app-erm-usage/pull/1

**Purpose:** update `erm-usage/files` interface id to be valid for Eureka platform

2024-07-29 10:12 UTC, pfilippov-epam approved these changes

2024-07-29 10:19 UTC, mykolam-epm approved these changes

2024-08-01 11:23 UTC, alb3rtino requested changes
I agree with @MikeTaylor on this: [comment](https://github.com/folio-org/mod-eusage-reports/pull/191#pullrequestreview-2210532311).

If this change is really necessary please increase the modules major version as this is a breaking change.

Also please make sure to merge this together with https://github.com/folio-org/ui-erm-usage/pull/476 and https://github.com/folio-org/mod-eusage-reports/pull/191.

2024-08-02 12:05 UTC, alb3rtino approved these changes

2024-08-05 16:32 UTC, MikeTaylor commented
PLEASE DO NOT MERGE THIS until we have concluded the discussion on https://github.com/folio-org/mod-eusage-reports/pull/191

2024-08-08 20:53 UTC, merged